import type { Metadata } from 'next'
import './globals.css'

import { Toaster } from 'react-hot-toast'

import { Inter, Poppins } from 'next/font/google'
import Providers from '../Providers/ReactQueryProvider'
import ReduxProviders from '../Providers/ReduxProvider'
const inter = Inter({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
})
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-poppins',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${poppins.variable} font-poppins boldonse`}
      >
        <ReduxProviders>
          <Providers>
          <Toaster 
        position="top-center" 
        
        
      />
            {children}</Providers>
        </ReduxProviders>
      </body>
    </html>
  )
}
